
networks:
  iot-network:
    driver: bridge

services:
  # ---------------- Zookeeper ----------------
  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - iot-network

  # ---------------- Kafka ----------------
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"
    networks:
      - iot-network

  # ---------------- Ingestion Service ----------------
  ingestion-service:
    build:
      context: ./Services/ingestion_service
      dockerfile: Dockerfile
    container_name: ingestion-service
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    ports:
      - "8000:8000"   # FastAPI
      - "8005:8002"   # Prometheus metrics
    networks:
      - iot-network

  # ---------------- Feature Extraction ----------------
  feature-extraction:
    build:
      context: ./Services/feature_extraction
      dockerfile: Dockerfile
    container_name: feature-extraction
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    ports:
      - "8002:8002"
    networks:
      - iot-network

  # ---------------- Anomaly Detection ----------------
  anomaly-detection:
    build:
      context: ./Services/anomaly_detection
      dockerfile: Dockerfile
    container_name: anomaly-detection
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
      - feature-extraction
    ports:
      - "8003:8003"
    networks:
      - iot-network

  # ---------------- Sensor Simulator ----------------
  simulator:
    build:
      context: ./Services/scripts
      dockerfile: Dockerfile
    container_name: simulator
    environment:
      KAFKA_BROKER: kafka:9092
    depends_on:
      - kafka
    networks:
      - iot-network

  # ---------------- Prometheus ----------------
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - iot-network
    depends_on:
      - ingestion-service
      - feature-extraction
      - anomaly-detection

  # ---------------- Grafana ----------------
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - iot-network
    depends_on:
      - prometheus
